// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            Code = "TEKNO",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@tekno-cozum.local",
                            IsActive = true,
                            Name = "Tekno Çözüm A.Ş.",
                            Phone = "+90 212 555 0101"
                        },
                        new
                        {
                            Id = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            Code = "GLOBAL",
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@global-lojistik.local",
                            IsActive = true,
                            Name = "Global Lojistik Ltd.",
                            Phone = "+90 216 555 0202"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<decimal>("MinStockLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MinStockLevel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Unit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000001"),
                            Code = "TKN-PRD-001",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Endüstriyel Ethernet Switch 8 Port — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 5m,
                            Name = "Endüstriyel Ethernet Switch 8 Port",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000002"),
                            Code = "TKN-PRD-002",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RFID Etiket 50x30 mm — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 20m,
                            Name = "RFID Etiket 50x30 mm",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000003"),
                            Code = "TKN-PRD-003",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Barkod Okuyucu El Tipi — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 3m,
                            Name = "Barkod Okuyucu El Tipi",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000004"),
                            Code = "TKN-PRD-004",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Termal Yazıcı Rulo — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 10m,
                            Name = "Termal Yazıcı Rulo",
                            Unit = "Kutu"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000005"),
                            Code = "TKN-PRD-005",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lityum Forklift Bataryası 48V — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 2m,
                            Name = "Lityum Forklift Bataryası 48V",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000006"),
                            Code = "TKN-PRD-006",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paletleme Streç Film — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 30m,
                            Name = "Paletleme Streç Film",
                            Unit = "Rulo"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000007"),
                            Code = "TKN-PRD-007",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Koruyucu İş Eldiveni — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 50m,
                            Name = "Koruyucu İş Eldiveni",
                            Unit = "Çift"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000008"),
                            Code = "TKN-PRD-008",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PP Kayış 16mm — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 100m,
                            Name = "PP Kayış 16mm",
                            Unit = "Metre"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000009"),
                            Code = "TKN-PRD-009",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Depo Raf Etiketi A4 — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 15m,
                            Name = "Depo Raf Etiketi A4",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000010"),
                            Code = "TKN-PRD-010",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IoT Sıcaklık Sensörü — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 8m,
                            Name = "IoT Sıcaklık Sensörü",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000011"),
                            Code = "TKN-PRD-011",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Akıllı Depo LED Aydınlatma — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 12m,
                            Name = "Akıllı Depo LED Aydınlatma",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b1000001-0001-4001-8001-000000000012"),
                            Code = "TKN-PRD-012",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yangın Söndürme Tüpü 6kg — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 6m,
                            Name = "Yangın Söndürme Tüpü 6kg",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0001-4001-8001-000000000001"),
                            Code = "GLB-PRD-001",
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kargo Paleti Euro Tip — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 5m,
                            Name = "Kargo Paleti Euro Tip",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0001-4001-8001-000000000002"),
                            Code = "GLB-PRD-002",
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soğuk Zincir Kutusu — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 5m,
                            Name = "Soğuk Zincir Kutusu",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0001-4001-8001-000000000003"),
                            Code = "GLB-PRD-003",
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GPS Takip Cihazı — demo seed ürünü",
                            IsActive = true,
                            MinStockLevel = 5m,
                            Name = "GPS Takip Cihazı",
                            Unit = "Adet"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MovementDate");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MovementType");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReferenceNo");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WarehouseId");

                    b.Property<Guid>("WarehouseSlotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WarehouseSlotId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehouseSlotId");

                    b.ToTable("StockMovements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000001-0001-4001-8001-000000000001"),
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed: ilk depo girişi",
                            MovementDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            MovementType = "IN",
                            ProductId = new Guid("b1000001-0001-4001-8001-000000000001"),
                            Quantity = 50,
                            ReferenceNo = "GRN-TEKNO-001",
                            WarehouseId = new Guid("97c62744-ea6c-4aea-b01c-08decd486689"),
                            WarehouseSlotId = new Guid("1ad8110a-e8f4-4b2a-b01c-08decd486689")
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-4001-8001-000000000002"),
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed: örnek depo çıkışı",
                            MovementDate = new DateTime(2026, 6, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            MovementType = "OUT",
                            ProductId = new Guid("b1000001-0001-4001-8001-000000000001"),
                            Quantity = 10,
                            ReferenceNo = "ISS-TEKNO-001",
                            WarehouseId = new Guid("97c62744-ea6c-4aea-b01c-08decd486689"),
                            WarehouseSlotId = new Guid("1ad8110a-e8f4-4b2a-b01c-08decd486689")
                        },
                        new
                        {
                            Id = new Guid("c2000001-0001-4001-8001-000000000001"),
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed: Global lojistik giriş",
                            MovementDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            MovementType = "IN",
                            ProductId = new Guid("b2000001-0001-4001-8001-000000000001"),
                            Quantity = 25,
                            ReferenceNo = "GRN-GLB-001",
                            WarehouseId = new Guid("f6715d0c-2cb0-4aae-b01b-08decd486689"),
                            WarehouseSlotId = new Guid("d2575c49-8a1e-4c9f-b01b-08decd486689")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("97c62744-ea6c-4aea-b01c-08decd486689"),
                            Capacity = 10000,
                            Code = "TEKNO-ANA",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "İstanbul / Tuzla",
                            Name = "Tekno Ana Depo"
                        },
                        new
                        {
                            Id = new Guid("f6715d0c-2cb0-4aae-b01b-08decd486689"),
                            Capacity = 8000,
                            Code = "GLB-MRK",
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Kocaeli / Gebze",
                            Name = "Global Merkez Depo"
                        });
                });

            modelBuilder.Entity("Domain.Entities.WarehouseSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int")
                        .HasColumnName("CurrentStock");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WarehouseId");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseSlots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ad8110a-e8f4-4b2a-b01c-08decd486689"),
                            Capacity = 500,
                            Code = "A-01-01",
                            CompanyId = new Guid("0dac2416-a292-4401-005c-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 40,
                            IsActive = true,
                            WarehouseId = new Guid("97c62744-ea6c-4aea-b01c-08decd486689"),
                            Zone = "A"
                        },
                        new
                        {
                            Id = new Guid("d2575c49-8a1e-4c9f-b01b-08decd486689"),
                            Capacity = 300,
                            Code = "B-01-01",
                            CompanyId = new Guid("d4a57ae8-a65b-47e2-005d-08decd47483a"),
                            CreatedDate = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 25,
                            IsActive = true,
                            WarehouseId = new Guid("f6715d0c-2cb0-4aae-b01b-08decd486689"),
                            Zone = "B"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.WarehouseSlot", "WarehouseSlot")
                        .WithMany()
                        .HasForeignKey("WarehouseSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");

                    b.Navigation("WarehouseSlot");
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.WarehouseSlot", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
